name: gradle-preview-ci
on:
  push:
    branches: [ "dev/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Add paperweight dev bundle to local maven repo
        run: |
          mvn install:install-file -Dfile=folia-api-1.20.4-R0.1-SNAPSHOT.jar -DgroupId=dev.folia -DartifactId=folia-api -Dversion=1.20.4-R0.1-SNAPSHOT -Dpackaging=jar
          mvn install:install-file -Dfile=paperweight-development-bundle-1.20.4-R0.1-SNAPSHOT.zip -DgroupId=dev.folia -DartifactId=dev-bundle -Dversion=1.20.4-R0.1-SNAPSHOT -Dpackaging=zip
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Set variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/*\/dev/}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            api/build/libs/*.jar
            platforms/*/build/libs/*.jar
